### ISSUE TITLE
Feature request: License Checker

### ISSUE THREAD

**Issue by nothingismagick** [lirantal/npq#117]
Would think that knowing about licenses is a good thing.

## Expected Behavior
It would be good to alert people to projects without a license. In my opinion this is more important than an email.

## Current Behavior
License is not checked.

## Possible Solution
Check out my forthcoming PR

**Comment by lirantal** [comment]
Agree but some times it's easy to omit it from the npm package, yet still have it on the repo so perhaps the marshall should do its best to look it up?

**Comment by nothingismagick** [comment]
There are several ways to license a project:
- with a LICENSE file
- in the Readme
- license header blocks in files
- in a parent folder in monorepos
- in the package.json


There are other projects that seek to identify licenses, but these can often have false positives, or worse multiple licenses. What I like about the package detection approach is that it is machine readable and hard to get wrong. Doing it wrong and publishing a package for public consumption is a sign of package immaturity - which means that the development team either can't be bothered or doesn't know any better. Both of these are dangerous.

That said, I suppose the https://github.com/iandotkelly/nlf project could be used to find the licenses - or that approach could be reverse engineered - the problem is that unless the modules are already cached somehow (as @DanielRuf mentioned in his enhancement request #97) this approach won't really work.

Another (MUCH SLOWER) approach would be to curl the git repository (if available), and parse the readme / LICENSE file remotely. This is likely to be non-trivial and provide more false-positives than would be really useful.

**Comment by DanielRuf** [comment]
Hm, this might be more complicated depending on the things that we have to check (different header types for example).

At least fossa and others already provide great solutions.

`curl` makes not much sense here. As this could be slow and requires specific things (Git, curl and so on).

We should do a simple check (license field and LICENSE file). This is sufficient in most cases.

**Comment by nothingismagick** [comment]
Ok - I am already checking the license field in the PR - will add LICENSE file detection and leave it at that. Sound good?

**Comment by lirantal** [comment]
Yep, sounds good to me @nothingismagick.
If either of them exists then it is ok, otherwise we fail, right?

**Comment by lirantal** [comment]
Fixed with #120 🎉
