### ISSUE TITLE
Updates to Jest, Babel, linting and test coverage

### ISSUE THREAD

**Issue by nothingismagick** [lirantal/npq#119]
This is a tracking issue for the PR I am about to submit.

## Possible Solution
Several packages (notably Jest and Babel) are outdated. Further, after updating, I noticed many, many stylistic errors i.e. using backtick instead of apostrophe in simple strings.

The main reason I did this though, was because wallaby.js wouldn't run on Jest 22. And I thought the coverage could be better, so I'll throw in a few tests for the laughs.

**Comment by lirantal** [comment]
Good catch thanks. I should have Snyk enabled for doing auto upgrades on this repo, what kind of outdated versions are showing up here?

**Comment by nothingismagick** [comment]
"babel-preset-env": "^1.6.1",
    "babel-preset-es2015": "^6.24.1",
    "jest": "^22.0.0",

**Comment by lirantal** [comment]
I realized you already opened a PR for it after I replied here :)
Thanks!

**Comment by lirantal** [comment]
Fixed with #120 🎉
