### ISSUE TITLE
Feature suggestion: advanced typosquatting detection

### ISSUE THREAD

**Issue by taobojlen** [lirantal/npq#142]
A recent paper ([SpellBound: Defending Against Package Typosquatting](https://arxiv.org/pdf/2003.03471.pdf)) presents some interesting techniques for detecting typosquatted packages. Instead of using the Levenshtein distance, they suggest checking for misspellings that are more likely (e.g. repeated letters, swapped words, and the like).

It might have some downsides -- e.g. does it require making a large number of network requests to check for potential typosquats -- but it reminded me of npq, so I thought I'd at least share the suggestion here!

**Comment by lirantal** [comment]
Thanks for sharing Tao!

**Comment by lirantal** [comment]
Would be nice to add if you wanted to create a marshall for it, otherwise I'll close.
