### ISSUE TITLE
`yarn global add npq` fails in 2.0.1

### ISSUE THREAD

**Issue by taobojlen** [lirantal/npq#154]
## Expected Behavior
`yarn global add npq` installs npq globally and, if using zsh or bash, prompts the user to install aliases.

## Current Behavior
The command fails with the following error:
```
$ /usr/bin/yarn global add npq                                            
yarn global v1.21.1
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
error /home/tao/.config/yarn/global/node_modules/npq: Command failed.
Exit signal: SIGINT
Command: node scripts/postinstall.js
Arguments: 
Directory: /home/tao/.config/yarn/global/node_modules/npq
Output:
Thank you for installing npq! We want to help you make conscious decisions before installing potentially dangerous packages.
To do that, we can alias npm and yarn to npq, so that e.g. `npm install <package>` will first use npq to verify the package and prompt you if it finds any issues.
? Do you want to add zsh aliases for npm and yarn? (Y/n) 
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
```

The issue occurs because yarn doesn't like stdin/out in install scripts: https://github.com/yarnpkg/yarn/issues/5476

## Possible Solutions
- Make it clear in the README that you should install with `npm install -g npq` and not yarn
- Only run the install script when installing from npm (i.e. add code in the install script to detect npm vs. yarn)

## Steps to Reproduce (for bugs)

1. `yarn global add npq`

## Context

See https://github.com/lirantal/npq/pull/150

I apologize for missing this initially; I tested with npm but not yarn!

## Your Environment

* Version used: 2.0.1
* Environment name and version (e.g. Chrome 39, Node.js 5.4): Yarn 1.x; similar error occurs with 2.x
* Operating System and version (desktop or mobile): Fedora 32

**Comment by lirantal** [comment]
great bug details and suggestion to workaround it, thanks!
