### ISSUE TITLE
Unable to query the Snyk vulnerability database for @nestjs/cli

### ISSUE THREAD

**Issue by xiniria** [lirantal/npq#172]
## Expected Behavior
When running `npq install @nestjs/cli`, the Snyk vulnerability database should be queried.

## Current Behavior
Instead, we get the error `Unable to query vulnerabilities for packages`.

## Possible Solution
It seems to be an issue with `encodeURIComponent` that changes "@" into `%40` and "/" into `%2F`, I am going to look into it.

## Steps to Reproduce (for bugs)
1. Run `npq install @nestjs/cli`

## Context
Trying to install the latest version of `@nestjs/cli` globally.

## Your Environment
* Version used: 2.0.8
* Environment name and version (e.g. Chrome 39, Node.js 5.4): Node.js v15.3.0
* Operating System and version (desktop or mobile): macOS Catalina 10.15.7
* Link to your project: N/A

**Comment by lirantal** [comment]
Good catch!
