### ISSUE TITLE
All remote data is undefined

### ISSUE THREAD

**Issue by omrilotan** [lirantal/npq#176]
## Expected Behavior

This did not work on my machine

## Current Behavior

![](https://user-images.githubusercontent.com/516342/100932687-e8f58080-34f4-11eb-8443-2f04f05487c6.png)

## Possible Solution

fetch interface does not parse responses correctly

## Steps to Reproduce (for bugs)

1. Install the package
2. Run npm install <PACKAGE>

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, Node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

Mac OS 10.14.6
Nodejs v12.15.0
npm 6.14.8

**Comment by lirantal** [comment]
Oh no! Checking your PR now

**Comment by omrilotan** [comment]
Addressed 772131e
