### ISSUE TITLE
Can't auth with snyk

### ISSUE THREAD

**Issue by Khazl** [lirantal/npq#183]
When I'm authed with the snyk cli `snyk auth` and there is a snyk config with my api token, npq is unable to query for known vulnerabilities:
```
    - Unable to query vulnerabilities for packages
```
But when I delete the snyk config `rm -rf ~/.config/configstore/snyk.json`, npq is running just fine.

So I have the situation, that I cant use both tools at the same time.
Reproduced this behaviour on two different machines.

## Expected Behavior
I expect, that the snyk cli can co-exist with the npq tool. So I can snyk test and npq i <whatever> in the same environment, without changing anything in my settings / configs.

## Current Behavior
npq will run into an error with the vulnerabilities check when snyk cli is authed.

## Possible Solution
...

## Steps to Reproduce (for bugs)
- Install snyk cli `npm i -g snyk`
- Auth with snyk cli `snyk auth`
- Install npq `npm i -g npq`
- Install something through npq `npq i axios`
- You should see an error
- Delete the snyk config with api token `rm -rf ~/.config/configstore/snyk.json`
- Install something through npq `npq i axios`
- It should work fine

## Your Environment
- Mac, Node: v15.8.0
- Windows, Node: v14.15.1

**Comment by lirantal** [comment]
Thanks, this should definitely work. Looking into it 👀

**Comment by lirantal** [comment]
@Khazl any chance you can upgrade to the latest version of npq if you're not on it already?
I'm asking as I can't seem to replicate the issue:
1. `snyk config get api` indeed returns for me an API token
2. npq install json shows me this output:
```sh
npq on  master [?] is 📦 v0.0.0-development via ⬢ v14.15.1
❯ npq install json
  ✔ Checking package maturity
  ✔ Identifying package author...
  ✔ Checking package download popularity
  ✖ Checking availability of a LICENSE
  ✔ Checking availability of a README
  ✖ Identifying package repository...
  ✔ Checking package for pre/post install scripts
  ✖ Checking for known vulnerabilities
Detected possible issues with the following packages:
  [json]
    - package has no LICENSE file available
    - the repository associated with the package (git://github.com/trentm/json.git) does not exist or is unreachable at the moment.
    - 1 vulnerabilitie(s) found: https://snyk.io/vuln/npm:json
```

(tried with `npq i axios` too per your reproducing, not seeing an issue there)

**Comment by yoavain** [comment]
I get the same error with latest npq. After deleting `%USERPROFILE%\.config.configstate\snyk.json` the error is not shown. 
```
Windows 10 20H2
nvm: 1.1.7
NodeJS: 14.16.1
npm: 6.14.12
npq: 2.0.17
```

**Comment by lirantal** [comment]
Looks like the common ground with both of you is the Windows OS, because I can't replicate it on a mac with latest npq version and similar major versions for Node.js and npm.

On Windows I'm not sure how it would've worked in the past either because there's a hardcoded path that it looks for here:

`snyk.marshall.js` line 14:
```
const SNYK_CONFIG_FILE = '.config/configstore/snyk.json'
```

I'm wondering whether the issue is that if this is a Snyk account you may have exceeded the API tests for it or something along those lines? If you use Snyk directly, and do something like `snyk test axios@latest` does it work?

**Comment by yoavain** [comment]
Running `snyk test axios@latest` works for me.

Also, I added prints to the snyk.marshall.js
The API token is extracted correctly by `getSnykToken()`, so the problem is elsewhere.

**Comment by lirantal** [comment]
@yoavain I can't reproduce this so it's difficult on my end to guess where the issue is. Could you add some prints to the returned results of the snyk vulnerabilities query? perhaps the issue will become clear when we understand what the API call returns.

**Comment by yoavain** [comment]
Here's what I can see from the `snyk.marshall.js`:
Calling fetch on this `https://snyk.io/api/v1/test/npm/axios/0.21.1` using my token results in this **403** error:
```
The org yoavain (.......) is not entitled for api access. Please upgrade your plan to access this capability
```
* This is a different error from having an invalid token, which gets **401**
* `getSnykVulnInfo` is hiding this error message
* Querying using `snyk test axios` did work for me (and gave an error when renamed the snyk.json file)

Not sure how Snyk licensing works and whether there's any difference between the API npq uses and the one snyk test CLI uses.
I can test tomorrow at work using a corporate token, on a Windows system, to see if I get a different result.

**Comment by lirantal** [comment]
Thanks Yoav, I'm checking internally.

**Comment by lirantal** [comment]
@yoavain & @Khazl to confirm - is this something you're observing as a new user of npq, or was this working for you before and now looks like a regression?

**Comment by yoavain** [comment]
For me - as a new user

**Comment by yoavain** [comment]
Hi Liran, 

Here are some insights from my debug session:

1. npq CLI calls
```https://snyk.io/api/v1/test/npm```
while snyk test CLI calls
```https://snyk.io/api/v1/vuln/npm```

2. Didn't have time to open a PR, but here's what worked for me:
```
const SNYK_API_URL = 'https://snyk.io/api/v1/vuln/npm'
```
in getSnykVulnInfo()
```
const url = `${SNYK_API_URL}/${encodeURIComponent(packageName + '@' + packageVersion)}`
```
and later the return data structure is a bit different so it should be 
```
  if (data && data.vulnerabilities) {
    return {
      issuesCount: data.vulnerabilities.length
    }
  }

```

3. Didn't have time to open a new issue, but I tried running with specific version (since I know the result should have vuln.)
```
npq i lodash@3.10.1
```

I saw that the `getSnykVulnInfo()` received the **latest** version of `lodash` and therefore returns no vulnarabilites. So there's some bug in parsing the version from the CLI...

Regards,
Yoav

**Comment by Khazl** [comment]
> @yoavain & @Khazl to confirm - is this something you're observing as a new user of npq, or was this working for you before and now looks like a regression?

New user and a free snyk account :-)

**Comment by yoavain** [comment]
Opened a PR. Had some problems with hooks not working on a Windows development environment, so I couldn't really test it.
This should only fixes the API issue. Will open a different issue for the explicit version not being used.

**Comment by lirantal** [comment]
Thanks! looking at these now.

**Comment by lirantal** [comment]
Closing due to PRs that have fixed this
