### ISSUE TITLE
Idea: run npq on existing project ?

### ISSUE THREAD

**Issue by lirantal** [lirantal/npq#20]
If you already have a project with a `package.json` that has malicious packages and you do `npm install` (where npq is an alias) it will not look at the packages since they aren’t explicitly added in the command line arguments. What I'm thinking is that another thing the npq cli can do is provide you with a way to install something like a git hook/npq run script (i.e: `preinstall`) so that anytime you do the `npm install` it will run npq on the packages from `package.json`.

**Comment by gautamarora** [comment]
possibly related, would be cool to run `npq`only as an audit tool so it can be added as a pre-commit check.

**Comment by lirantal** [comment]
Volunteers are welcome to re-open and discuss, closing now for inactivity.
