### ISSUE TITLE
incorrect: package has no README file available

### ISSUE THREAD

**Issue by OmgImAlexis** [lirantal/npq#205]
If I check `node_modules` I see a `README.md`, the github for typescript and the npm page both show the README.
Not sure what todo about this.

```
❯ npq-hero install -D typescript
  √ Checking package maturity
  × Identifying package author...
  √ Checking package download popularity
  √ Checking availability of a LICENSE
  × Checking availability of a README
  √ Identifying package repository...
  √ Checking package for pre/post install scripts
  √ Checking for known vulnerabilities
Detected possible issues with the following packages:
  [typescript@latest]
    - the package description has no e-mail associated with author(s). Proceed with care.
    - package has no README file available
```

**Comment by arthurdenner** [comment]
Interesting report. I looked into it and noticed that `npq` just gets data from the NPM API and check for specific properties.
In this case, the NPM API is not returning the `readme` property, therefore causing the warning.

You can see it by visiting https://registry.npmjs.org/typescript. There's no `readme` property in the top-level JSON.
However, https://registry.npmjs.org/ts-jest has a top-level `readme` property.

<details>
<summary>Screenshots taken on https://jsonformatter.org/json-viewer</summary>

![image](https://user-images.githubusercontent.com/13774309/155726678-56ae5628-6707-4705-9b34-eca5e59a906b.png)
![image](https://user-images.githubusercontent.com/13774309/155726562-d7c654c9-cc4c-4f8b-9169-8394205dfd63.png)

</details>

**Comment by lirantal** [comment]
Indeed the README marshall inspects the package's data (called a pakument) because that is what you download in the tarball and can be different from GitHub. Happy to consider other ideas but at the moment I feel this is a good measure.
