### ISSUE TITLE
Support npm's (typo-)aliases for install

### ISSUE THREAD

**Issue by baranor** [lirantal/npq#207]
## Expected Behavior
Running `npq isntall <package>` does run npq's checks. (note the typo in the  command)

## Current Behavior
Checks are not run, but `npm isntall <package>` is executed directly.

## Possible Solution
Add the aliases `in, ins, inst, insta, instal, isnt, isnta, isntal, isntall` (see https://docs.npmjs.com/cli/v8/commands/npm-install#synopsis) to https://github.com/lirantal/npq/blob/master/lib/cliCommons.js#L7

## Additional info
The same problem applies
- when setting up the alias for npm
- with the other aliases for `install`, that npm has (listed in the "Possible Solution" section)

**Comment by lirantal** [comment]
That's a nice idea @baranor, thank you for raising.
