### ISSUE TITLE
Logo needed!

### ISSUE THREAD

**Issue by lirantal** [lirantal/npq#21]

**Comment by Yasujizr** [comment]
Hi,

If you want, you can look at my work from my profile. I would like to help you with your logo. Could you send us your wishes and sample logos that you like?

**Comment by lirantal** [comment]
hey @Yasujizr, thanks for jumping in!
I believe @gagyibenedek had also been working on it. Maybe you guys want to work together or share ideas?

**Comment by Yasujizr** [comment]
Oh, sorry.

If he accepts, of course. But I do not want to interfere with someone else's business. Maybe share idea. If he accepts.

**Comment by gagyibenedek** [comment]
Actually, I had an idea, but I lack the skill to execute it.
What I thought was, to basically switch the letter Q to a quality badge logo ([something like this](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAALsAAAEOCAMAAADmPpYqAAAAYFBMVEX///+fyOOopaWbxuKjoKCin5+YxOH8/Pz4+Pj1+fzg39/r8/mrqKi/vb309PSwra3O4vC11OnY6POmzOWqzua5t7fD3O282Ovb2trFw8PT5fLr6url8PfU09Pv9vrPzc06zZhhAAASiElEQVR4nO1d2XbqvA4uGZkDBGhpGN7/LU8SAsi2JEuOYfes9etiX+yG5IsiS7Imf31Fo1uVHObsFT9VklQ/8Z4Yi6bLLEmSvJqSV6yr7ookP3wQlYyWyZ3yhrigyYYrstNHgfnp9ECW5LjcNHnyvGL9YXA8AWRJfkEuWGevC5LVx/FxVAFkSX5z/t5kxgV/ifHzPGHBm9D/lsQfkoQDZ71aS+U/AupS42DLDgDdxf0zbwc+SSsbW4tu+dCV5cqBniR/RsevMxdcJzf9ipwvsb9mf2W1nlDsSZZVt0tF/O2PrFac7QN88i8fZvy6QR9oKxkZfVLiy9syz/Pl6sfG7ypAEWWOP1k2t9XhcKP8oRHQH4KbZas51M7rIOTdjUyQ61OSd4/I8kNs5Q/XY5bcnp5uEwq9JfAFm9NraWSRxclajy1zbvNmum4IFSOknwfwpSF3hCcaShcHY5a14k/rERFl1elyO9xlBVJcxiOWMwpl+NtHlfgKe8LbKKqPXH4Uuq2CxtH0w9hjLtZPY48ZB5mO0yf/YQ8kxlVkENzpn2PX+Fud1cqqw+p0ut1up9PqUGVKKxZ1rbobUhJ2tbrM17ZtKdfzy2opfoGoOnIueWiL+zbnLGI5v1WO/ceIjAuG0I/3ia139kOHUV80/Tn44Ue1qzf+cS1wluEmlV74UWWG3dZly5uWT+tbwqHPsIhmIHFmNQ9MBvxUzPqv4mGnRSarwtUZHrm53zaakiQ3R1kyzohcaMmJs1rnRHiohX4bu0coT5TgLEct13K67iwKyZr8EIM36wOBfggJ6mg6v7VmfLlctqqPM4S8uJSz6+Lc0eI6478OZTu6kOC8WbfUtLQWGI/pSuQ+5QfyXuVid9zWk6JI0+L+z6TebnYL8g2mB1Iou/38QEnlU5xTVu++oFP3uW62kxbvxKbuDba/V+JXN5G75IvbrGTeEr6Qzscaw/3Enxb1cYH+UuQvtbqBgy7aU2do/ne2aYGTuF/8rzcz5NdrWtcDWnLYJX46+ukW3wLgD/jfCPNLUhMDYn20qR87FvVfbAsh8AH9FkEvEFfWN/bLDJI7veqQ91R8u5Ljj21mrKL05QEQ6EextBi8Tzd68LyL5nHUXejnOgR5z/r6rATvSVLxG1P3x996cQHoj/bteJn3eZdc0DSzaxiuwUwfwO9tqSdNbE8e148RGkc57hhDJKTUlhuOd77yDyYCVlmvfRwjL0/WW0uW2aL5NyRklsDOiAZoRozSb/O2zIrz7hao39pJoP1oeRmo2Jo3disnBt4JUuG4xNl+UDToLef35q0JZSMJOLlpsY4ssxARugO+XGIAeEdsIFRoLGGPCr0FvxUgYB3ggTB/zAr2bONCd6wUZl9lMUrkk5kSc4wNvQX/Cx+ASY1EZLDFar7zTqwci1p+qWGkkPoKWb7Y8SVN7TQT46lnXwvptZO0ZDEksmIh54OZbrPYh+lZ+St9U1PZuMtVVA/qxEvMFS4W9gGM8Or2ekPkHSUvkXekHgZ+zbNYYgY3S8z4SQpDIM7OWRBeXbsSY7C9FvPxIQPiH0wMqXH1pC/GN3e5brB9I+fi7vETsUZ9/gRlfLJkwU+RMkyD7TO5Zq8fvynFP5lMIBjXoWXSISWaSDFiIt9i7MWLhwrGQ2ce8QyoTMWUCORD3XQNYHvLE/mvUrgHxBzaHEG/PhHRX8OkBrFdxXjo1+DBbRs9idxUq1fFTgneXrFKIONLApOB/saUvsKVqmC7YWcUzpsh8eT2M68GaZhyUUy4UhXsM9iucYGMXzKR7bx3b4hdykDQ+Q3UF0rGw4XCMDXrohZsFM8QGblJTS3oGsbDLRRX2dhFi9joKdQyCk/GDZMqlgpYrWw6JJ97Ir9h390NpMgZD91JPh2w4mUGGiaxyKROiFTDeGPfzZaUVmzkF9ZtLUScS1uaYPGrWZeuFOGHKt7HWObdoIb0aZk0LdJisj3+OlH1Afz597jvrvG9Ady5cgLfBeoYxmfg2XRIpge0/96cqfQpoHKx23zv2W8ARY4T+CX/YcDenPBk06L+5nLWBM3Ou822LnAxBG7cF8P2uwqkAvYwPoCLe42neqV0xvkBBJ7Ugk9sBHi4VH+xb1wQsi2mHXZXmE+gZALkMXDw0DKhOi4VSDhLqL2DGp4q8lgCKUXjxlDN7NGvi2lyDW3Ru4JsQkNgNyJGGPgc/B2VTCRTp4OOKxsQLyCKBKxdN6Lmwb6D8n9HcZ7K+kBFg2K3AwZIkgo4wKRVHcF5MhIOFQ0iDkgroGvDgDdDO5HB4OkgPsTu7i7Q7ieucZmJWweCZ/IPKbAajijj+Q97TUPsqHofA55LnUCz4RgnIqa6DMM+Kb7x+wVCN7DbWyeqJeEQiF0Pnk9YweDOyeY7UUJThWLXgvfk2qBhtcPBRAmNrSWNtepzujXgfRlOGCsQYnd8BwV2BfjSm5wNkBlHHQH97s/tScH7oRvYZWvVddnA1kMQ4JCBF0DndSQmNB6fQLBNFvk2kpR4wdomhPHIDkXgi5kkwC6JNsDwkovKlXg0hf/6syTxYteSoCRhAQySCGZ5oAU3OXhDQWRJJjMC6MAHRgszTI8GrxWCez7BM83kLkGSYDKIjKEBGCMXQ9Sfw3SsIBop2nkLCilgKBYPLgEPniqdhx9H8kysONwmQWgQqnciTvDUIj9k8AkYJ0mKTwBdorCgmiEi8I8QB1PzDn1l72IVqRmJooHbVSopM/haXCwVKCvvYhVuu/33Afa5JPnad5xwI1hgP6NX4I1MEU1eRQPFncuWNZ6cDlisXkFNZbFJLw8Kafzdk1qAJgyNjEHsEjXjVzTGsmGrwn947FDgvR8bA+r+l8+7kOebTp4cJbBOHi1p1Wd29DspJq6t9SgscZ6v1eBU1v6OHVbH8e6ro2Z2fYFhUdtL2KNopPnVfjHybRIQDCuplpo57x9XF3vTV+BlzyjmZ9nee4psQgq6PSy/DDWzMHZHqdHOxLMAGiY+NXzfg6zpaghDaFiOATVzdaQr3b6yDGwli6yOo0W+fK5Eum09A5qGT04/r8J6b9JXMxZbxgRT4vRKNOt/8FqxxNoeco7wsMbKI5F9TNPjgItRNMaCxwvxsbqr8oK3MsJ9OWNbBxW5mTCXTDY+7EZKHLc8WMXYF9F0b6xWhvGdgtgxyO/od2yYqvDU6ZHI+8+EXG4UEXPA9hPBvqLm4jNQyWCBi+zAFfAjvdNGgaQ3tjeGjOI+jO2+kmAn2GFWv0v2+YFkehWuglz6W+WdJWIwXlHeqcYOHVFkfKyg4YPNmXkj8eFkSAzS/CDps3H3r2a7R+T+oAeZEuOyXTRPB3GajSiapq5aQwYIV7eL+myQuIGZ0pRVXympMMoqkLCLaCQNahOM4h55G4QcuiHsWCOqiO9Y2YfVwxi9OcvqYkULMySTqJwMjys149q0EejmngsNu4hGARGhKLMkLGpHn5XtwVuXJe2rxBbQ7jOPCN5OVBE1YoLFSs0IsMe2RGp5dssRqMCFX8EzmxXLJkdpNXebzckYo3/oGDd9znpxeT8lB91KOFAFYomgk5Iry15aJZwLz1bDT2ltVfqxU9g8QsMPubSXy2w/jvVOLK1kA5Aeb4za3w6/dj7bJmgIykCFE/DjB+h4NI1nhoszkePrGuxWFlsncMxP4/C0bHtnurrgW4c+aP7MxE01eKB7NI1/tigCngzJMMiRlhAvdI+m8c/nNE/uGGimQ/8KMwFi26wGshWdQfxSHcBjI7pa9NJVm042CATR+H523pKA7x1ha6bcbf3o2xfcotlv2XA01g8Wzr3O8UK/2abrhuCA73/xpBQ1+8Qifv/RyEb45pRDOtt916nbzNH91/64I7Jp6Kkx2FM9LvzjuAcPZRWta7uOmm3d87mfYjjZb4+7BZ0FbGTzBzNvWKw/ZuN0qFriB0gik8bM28xm18VicZ15Upf06M7kMVI7b7lZrX5UDTHlupnf6Imj48aCDjSnsxZZdbpd5vN506wlky8xakibka/GTh1tqImj7Rtdoox7pZ2ccdNep7S4ZKtIR01wc7OSYPRTrtU63klybL0EOCBGQUx7eyIdlCMi3upl2Uq7auf8NO+Y87C9RwbkS8XRRc0t8diiqPPf2X70O6uE8Oci2xeoElESHQnTWrLVhcPfXA6ysxsiirviKJ7WBlany7wxGTdt5pdVlYvOC+go4gh1yShT4wX645Gq6tBRtdQflhQVu2cUaWyKil2yn4pIUc+e+n/GLtwL/oc98rm4sq3w38TORJbfQHEP2lSdIzQeuyT9LiZsxnfGH4cgAomf7xT5VFynLzdpXZdmPu5YxOzUND+3gwM/8vmmRhYoy55H7zDliV567NXL+cqEH9WsfoGofpZXF+hphZ86CLg7hWWCkY+j7PbF3bFX3UkVlpcbevydJdTlpbozP4u5aXrSet40yMY60G65Onzd+snL5ei4iYqCpIZYj58+M5xMlrRCQGrRqKZzBOGxp2zVTMs1Ue0adTc9hrA0+jNQXKI24M+ca45NQwYuCVJAFV0NqqiEoWlna2IWfbjfJWogQEez3baAVS+2u2PndJxpGeDVNumWyofEpy6r1OVkYEbd3Iu7EmGDf6nCrh8gLT4Cvwf+yCa9/ttgPFb8aqQgoY9778NIPwDfSEPClpiXxGf4GN8p1JXAAoF0Wgv/jabJajPBpvblpPZ7pk+gSJn1Q4WoBTaMrEYbWEu67h3BjMi89jS0JxtJNqtJsBg79Ism60nG0RzTQ557kiDrqnNFIXR73ARWIhGHnB6hwlxe/shzczN8f7emW9Z7HEBO6fvY2WjulI/iXcrGreccKZ9ut5BoxkEAYW1lbuPng85+DmL13PQNRxFWD1lQTdrfhVd00U4vYfexlvAWG/RZs3YRPjg42xLvh96PZMYownslkHbh+0zLJ4jfwi6bvRMxwl8/70tAxOgfBFhvwp4aozXGmD4iJwm9wy+gJvzaquFerAq+R93VQtqIyEFCzilgMYh4lq3lh6458EZdh4VdDnkWjamNRfTTJumzI3v2+zjBBhiZ+y+NIjfuuIr6Kzqx/SndpN3NcVs/XXtjQsLj/+rj+Tory9mOPaKnGDf7FiPPWAGrwM1wqp4rJe3L+DyliPGFRjKkCzIPOgvy6es9RffHlC1NhtAqDsnoKLoTLx+635Hlh+uaXmP7Y5rjMSbOetN1G6OmegTJz2noydJzmnMmJtH9MV13gaMqdD+P649pjvaYIJPGlJ8tqtBoW5ns3yuXS1R/TKkoXD9WqaYi+mMz1ZOxR+vMA/LywaQUGedYFX2fdDzs37oHY1zT3SGi0OgejKo4+aEwPfZo/hjjuqPY0XvohCaaE6/0w3DtrHQqYvljqqdSVlGpZiMFVbWuO25YlLoqkhOv1M3EU8t/4o8pbSLlfes66+P4Y1rXnWKYcvhLFH9M6QOSgqp14mP4Y765kdYjaQWhk70YQqN13WnFrPuAMfwxpZgyBvHz/phyt8fZFB300QcsaUWGHfiqNBSj/bGxuz1ISn9stNAo3RCeV8plPzaoOjJAYJJuDzPWH4v7mZUCONKJV253PDpZG1Qd549FFRmtPzYuqKoUGSRAYJIyqDrKiVfu9rxmXOmPEdsYGameJHGfdI7dGH9MOSxS4LZ+Lqga/0nKjYx3AdH0Bo9bdccR/tg70hWf8sd0rrtMo33KH1O67jJLQv0anxwkPETBITSikhZ7IqMutOC4l1H8LtCZU6H+GFpjtb9S1lFoBFGh6Zd5iY0XDPTHXNc9HYbrY8Ik5RDqjw268OwOuQsMqtpcSJ/TErGgtvghyG7m9d7OcMQwf8z+uMX+tW4Q7OKPi4giWCoLa0RfmD9mLqrUYIBrcOWaGNm9GwbZqgsK8seMR7xG/t+f7xbDypWZs1qs7NLMuCDEH4MyXdS2bXaEVqEPHJPn/NaYgR/gjwHjjZQR2qtVY7xtfwxZjvC8hwB/7IXcnZX45bhpqqSi9VtUol/qUu+PPYKH2KzEjmxtobm36Y9RG/THfEF9UPXR/0LKguj5OJkJLNJlWQzOh1po+sWY7mntYTBPmYc2vhijwO8MVGvJVstS4nIncz+ouz18b1YHXlsXx1+M7t6/PvKOIYy1KEXS0FL8pbs9MidzNAGfQWs/QDn6+zprWAIAtMG3l2l7W3MKTy+nRm36Xhr2Tf0dPno6VXqXYxZueCLR48sH5M8f7tYbCsZlNKiLkDrSX6fC/9NUBwMYnOg3dQRJ6L7kglRFH1SNWY+npdJn1GnqlVRo9CUK9W0oQdal91Pf1jUpoW4bERiFqNM39ZCJaTdhHTaGrvvJ2MT1/wAvbR9ZUvEJDgAAAABJRU5ErkJggg==)) in a way, that the hanging part of the badge looks like the tail of the letter Q.
You could execute this idea if you like it or come up with something totally new, however you prefer :)

**Comment by gagyibenedek** [comment]
I'm glad you like it :)
I was thinking about using a NPM like red (#cb3837) because NPQ is basically a wrapper around it. But this was just a quick assumption, I feel that any other color would work. Maybe @lirantal has a more concrete idea about it?

**Comment by lirantal** [comment]
I'm good with whatever you guys come up with :-)

**Comment by jackingpanda** [comment]
How about this? @gagyibenedek @lirantal 
![logo](https://user-images.githubusercontent.com/20648882/38747297-9e902a18-3f74-11e8-97d3-2077211958da.png)

This is another alternatives, the last one is the logo I presents above.
![alternatives](https://user-images.githubusercontent.com/20648882/38747389-f033b146-3f74-11e8-886e-92a271d3f482.png)

**Comment by jackingpanda** [comment]
Is this good? You can freely use this, I'll sent you the original files right away if you accept it @lirantal @gagyibenedek 😁

**Comment by gagyibenedek** [comment]
these are GREAT! it's how I imagined it, just better :D
What font did you use for 'npq'? It looks really good :)

**Comment by lirantal** [comment]
I like them too :-)
But how will we choose? so hard! 

Maybe I'll just poll them on twitter 😸

**Comment by jackingpanda** [comment]
@gagyibenedek it's Moonhouse, you can find it [here](http://www.fontspace.com/nimavisual/moonhouse), I'm using it with "NPQ" (with capital letter) :+1: 

@lirantal you can use a poll, when it's decided, just mention it to me and I'll give the requested one. For myself, I like the last one :smile:

**Comment by jackingpanda** [comment]
@lirantal that's amazing to see how much the people reacted to the poll, I'll prepare the logo right away after I got home.

**Comment by jackingpanda** [comment]
@lirantal are we going with the the number 4? Here's the link for the [original editable files](https://drive.google.com/open?id=1At-nvO0eMyKXf9jWMfWsGOSsLhZ3WHoq). I put several sizes for the icon and also in vector format for flexibility and scalability.

If it's good, I'll sent a pr. :wink:

**Comment by jackingpanda** [comment]
Hey thanks! It's a pleasure to contribute on this project @lirantal ! I've sent a pr :)

**Comment by lirantal** [comment]
Addressed by #33
