### ISSUE TITLE
--dry-run option not working

### ISSUE THREAD

**Issue by shivankar-madaan** [lirantal/npq#214]
Hello Team, 
   When I am trying to use the dry-run option. There is no output from the cli. Could you please help.
   
```
root@ip-172-31-20-64:~#  npq --dry-run express
root@ip-172-31-20-64:~# echo $?
0

root@ip-172-31-20-64:~# npq --dry-run
root@ip-172-31-20-64:~# echo $?
0
```
   
   
   Thanks

**Comment by shivankar-madaan** [comment]
npq install express --dry-run

**Comment by lirantal** [comment]
Indeed. @shivankar-madaan would you like to send a PR that updates the README with this information so it is useful for others like you?
