### ISSUE TITLE
Ideas for more npq marshalls

### ISSUE THREAD

**Issue by lirantal** [lirantal/npq#22]
some examples:
- how about trying to identify the author? like if there’s no e-mail associated with the repo/npm account user then it is suspicious 

- some malicious modules don’t have some fields in their modules’s package.json like the repo URL because their malicious and don’t put their source code on github. so maybe check that too

**Comment by gagyibenedek** [comment]
on it!

**Comment by lirantal** [comment]
Addressed by #35 and #29
