### ISSUE TITLE
scripts.marshall failing when installing a package without specific version

### ISSUE THREAD

**Issue by baruchiro** [lirantal/npq#244]
```
❯ yarn add react
  ✔ Checking package maturity
  ✖ Identifying package author...
  ✔ Checking package download popularity
  ✔ Checking availability of a LICENSE
  ✖ Checking availability of a README
  ✔ Identifying package repository...
  ✖ Checking package for pre/post install scripts
  ✔ Checking for known vulnerabilities
Detected possible issues with the following packages:
  [react@*]
    - the package description has no e-mail associated with author(s). Proceed with care.
    - package has no README file available
    - Cannot read properties of null (reading 'version')
```

You see, `npm-package-arg` returns the version as `*` and then, on `scripts.marshall.js`:
https://github.com/lirantal/npq/blob/master/lib/marshalls/scripts.marshall.js#L20:L23

It is not considered as a latest, and instead it parsing the `*` by `semver.coerce('*')` which return `null`.

I sure we need to replace the `*` with `latest` somewhere, but I'm not sure where, because I don't know which change created this bug.

**Comment by lirantal** [comment]
Ahh indeed. I've fixed something related to that but looks like the issue is deeper.

**Comment by lirantal** [comment]
@baruchiro this should be fixed now. Can you retry and confirm?

**Comment by baruchiro** [comment]
Confirmed
