### ISSUE TITLE
Collaboration with Overlay

### ISSUE THREAD

**Issue by baruchiro** [lirantal/npq#265]
Hi, we just launched [Overlay](https://github.com/os-scar/overlay) - a browser extension helping developers evaluate open source packages before picking them.

![Picture1](https://user-images.githubusercontent.com/17686879/235855301-aac850c0-cf05-4e9b-8fe6-fa16a381780d.png)

I'm thinking about extending `npq` to support more package managers and more advisories.

WDYT?

**Comment by lirantal** [comment]
Package managers, how? `npq` is an npm's package.

About advisories, I was thinking of plugging in deps.dev and osv

**Comment by baruchiro** [comment]
Why we can't expand `npq` to do something `npq --packages=golang` to support also Go commands?

**Comment by lirantal** [comment]
No reason it can't happen, I'd just be surprised that Go developers would install an npm package to do this sort of proactive scans.

**Comment by baruchiro** [comment]
Yes, it is something to think about...

**Comment by lirantal** [comment]
Closing for now :)
