### ISSUE TITLE
Legacy "--save" option is not checked

### ISSUE THREAD

**Issue by daniele-pini** [lirantal/npq#300]
Hello, I'm trying `npq` and I noticed that running the command with `--save` seems to skip all checks.

Yes, `--save` is unnecessary these days as it's the default - but I never got the memo and was surprised no check was run.

## Expected Behavior

```
$ npm install --save express
⚠ Supply Chain Security
  ✔ Checking for known vulnerabilities
  ✔ Verifying registry signatures for package
  ✖ Verifying package provenance
  ✔ Identifying package author...
✔ Package Health
  ✔ Checking for typosquatting
  ✔ Checking availability of a LICENSE
  ✔ Checking package maturity
✔ Malware Detection
  ✔ Checking package for pre/post install scripts
  ✔ Identifying package repository...
  ✔ Detecting expired domains for authors account...
  ✔ Checking package download popularity


Detected possible issues with the following packages:
  [express@latest]
    - Unable to verify provenance: the package was published without any attestations.

? Would you like to continue installing package(s)?
```

## Current Behavior

```
$ npm install --save express

added 103 packages, and audited 104 packages in 7s

19 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

## Possible Solution

It's quite possibly related to https://github.com/lirantal/npq/issues/34

## Your Environment

* Version used: 3.4.4
* Environment name and version (e.g. Chrome 39, Node.js 5.4): Node 20.11.0
* Operating System and version (desktop or mobile): Debian
* Link to your project: -

**Comment by lirantal** [comment]
Thanks for posting @daniele-pini 
It seems like you alias npm to npq. Did you alias npq or npq-hero? would be great if you can show how you aliased it :-)

**Comment by daniele-pini** [comment]
Sorry, didn't mention that. I followed the suggestion in https://github.com/lirantal/npq#embed-in-your-day-to-day:
```
alias npm='npq-hero'
```

**Comment by lirantal** [comment]
Thanks! I've landed a fix now and it should be published in a couple of minutes.
