### ISSUE TITLE
Exceptions are thrown due to inaccessible data elements from the package metadata

### ISSUE THREAD

**Issue by lirantal** [lirantal/npq#38]
# Actual

![image](https://user-images.githubusercontent.com/316371/39599931-eabac68a-4f25-11e8-9227-b6f17374db88.png)

# Expected

If data isn't available for some of the fields it shouldn't throw exceptions 

# Reproduce & Notes

Reproduce: `npq-hero install getcookies`

The relevant problematic marshalls are the readme trying to access an inexistent property and the pre/post install script marshall probably unable to access the latest version tag.

**Comment by gagyibenedek** [comment]
on it!
