### ISSUE TITLE
Feature Request: take into account package size

### ISSUE THREAD

**Issue by styfle** [lirantal/npq#62]
I wrote a tool called [Package Phobia](https://github.com/styfle/packagephobia) that shows the npm install size (package + dependencies) before you install the package. Is this something that would be useful in gauging the safety of a package?

I can think of two metrics:

1. Max size threshold, say 5 MB. Any package larger than that threshold shows a warning.
2. Comparison threshold of previous version, say 20%. Any package larger or smaller than that threshold shows a warning.

Package Phobia has an [API](https://packagephobia.now.sh/api.json?p=express@4.16.0) if you are interested 😄

**Comment by lirantal** [comment]
I'm not sure how a package size would be warranting caution in terms of being too small or too large... ? Plus, I think having a dedicated package for that with Phobia is probably a good solution on its own.

Thanks for showing the love ;-)

**Comment by styfle** [comment]
@lirantal Try to run one of the following (or both):

- `npm install sindresorhus.js`
- `npm install npm-bomb`

A max threshold in this scenario could give a warning before you waste your time and disk space.

Also, are you familiar with [eslint-scope](https://eslint.org/blog/2018/07/postmortem-for-malicious-package-publishes) getting hijacked? Many users already had this package installed so it would be good to get a warning when the source code changes past a certain threshold for a specific version and maybe catch these types of hijackings before upgrading.
