### ISSUE TITLE
Unused dependencies contain vulnerabilities.

### ISSUE THREAD

**Issue by ronperris** [lirantal/npq#74]
The `docs` script in package.json currently fails because the file input path used contains no files. The library `doxdox` contains vulnerable dependencies and appears to be abandon by its maintainer.

## Expected Behavior
Running `npm audit` should result in 0 vulnerabilities found.

## Current Behavior
Running `npm audit` results in a vulnerability report.

## Possible Solution
Remove docs, docs:api, and docs:code scripts along with their dependencies.

## Steps to Reproduce (for bugs)
1. Run `npm audit`.
2. Check the return status.
3. Notice a non-zero value.

## Context
Projects that don't want any known vulnerabilities can't use npq.

**Comment by lirantal** [comment]
Not exactly a fix but will update the out of date yarn file and remove the opensource-check package here https://github.com/lirantal/npq/pull/77
