### ISSUE TITLE
Feature request: prompt the user to confirm adding npq as an alias to npm and yarn

### ISSUE THREAD

**Issue by lirantal** [lirantal/npq#90]
Provide a better DX for users

## Expected Behavior
When someone installs npq they would probably want to use it in an integrated manner with npm and yarn by aliasing it.

On install, we could prompt and ask them whether to add the alias to their shell interpreter and then do it for the user.

Once we do add this feature we need a way in npq to remove the alias as well so on uninstall users won't have any leftovers.

## Current Behavior
No alias is being added automatically and the user may not know that they need to do it

## Possible Solution
1. Detect the user's shell
2. Open the relevant shell profile 
3. Add the alias and save the file

**Comment by DanielRuf** [comment]
> Provide a better DX for users

👍

**Comment by lirantal** [comment]
yeah let's add `preferGlobal`

**Comment by taobojlen** [comment]
I'd like to give this one a go if you're still interested! `preferGlobal` [has been deprecated](https://docs.npmjs.com/files/package.json#preferglobal), so I'll skip that part.

Are you still aiming to support Node 8 now that only versions 10+ are maintained?

**Comment by lirantal** [comment]
@taobojlen still interested if you can wrangle up a good PR for this. Happy to discuss first how you might want to implement it before you take it on. It might not be as simple as just prompting and adding it to their shell as you'd need to check if it's already then in-case, detect the correct shell etc.

Indeed can let go of Node.js 8 if your PR requires it.

**Comment by taobojlen** [comment]
Great, thank you! I've started messing around with this a bit; roughly as follows:

- In a `postinstall` script, detect the shell using `process.env.SHELL`. This works for bash and zsh; I still need to look into Powershell and Windows Command Prompt. If no known shell is detected or if it's noninteractive, abort the script.
- Retrieve the necessary config for the detected shell. E.g. bash uses a profile file at `~/.bash_profile` and the alias command `alias npm='npq-hero'` (and the equivalent for yarn).
- If the profile file doesn't already contain the alias command, append it.
- On uninstall, detect the shell again and remove the alias commands from the relevant profile file.

Does this sound reasonable? I could detect whether npm and yarn are installed and only add necessary aliases, but a simpler solution that always adds both might be preferable as a simpler start. Let me know.

**Comment by lirantal** [comment]
Nice. It doesn't have to be "all or nothing". Meaning, if we can support some shells but others are hard to work with (detect/etc) then it can be available functionality only for those which we support.

Sounds good to me to go with. Thanks!
