### ISSUE TITLE
Support for onload-script

### ISSUE THREAD

**Issue by DanielRuf** [lirantal/npq#93]
## Expected Behavior
`onload-script` in `.npmrc` should be able to run `npq` before any command.
(We should probably add some more examples for example for `preinstall` in `package.json` for different users.)

## Current Behavior

```
onload-script = /Users/druf/.config/yarn/global/node_modules/npq/bin/npq.js
```

```
npm i crossenv
  ✔ Checking package maturity
  ✖ Identifying package author...
  ⠴ Checking package download popularity
    Checking availability of a README
    Identifying package repository...
    Checking package for pre/post install scripts
    Checking for known vulnerabilities
npm WARN onload-script-test@1.0.0 No description
npm WARN onload-script-test@1.0.0 No repository field.

+ crossenv@0.0.2-security
updated 1 package and audited 1 package in 1.05s
found 0 vulnerabilities
```

## Possible Solution

See https://github.com/DanielRuf/onload-check for some sort of prototype.

yarn v2 will support plugins and more and not sure how we can support others too. 
https://yarnpkg.github.io/berry/features/plugins

But the `.npmrc` setting `onload-script` is totally underrated.

```
// taken from https://github.com/eush77/npm-autoinit
'use strict';

var spawn = require('child_process').spawn;
var spawnSync = require('child_process').spawnSync;

var autoinit = function() {
    console.log('starting...');
  // Block event loop while package.json is being constructed.
  spawnSync('sleep', ['1'], { // just an example, here we should run npq, but this does not block the event loop
    stdio: 'inherit'
  });
};

var installing = process.argv.some(function (arg) {
  return arg == 'i' || arg == 'install';
});

var local = process.argv.every(function (arg) {
  return arg != '-g' && arg != '--global';
});


if (installing && local) {
    autoinit();
}

//process.kill(process.pid, 'SIGKILL');

```

## Steps to Reproduce (for bugs)

1. Load `npq` through `onload-script`
2. Run any npm command (yarn does not support `onload-script`)

## Context

I would like to hook npq in projects using `.npmrc` which is tracked in the project itself.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, Node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by DanielRuf** [comment]
Maybe we could add the URL check as check.

**Comment by lirantal** [comment]
@DanielRuf TIL about `onload-script`, pretty cool.
yarn doesn't support that?

**Comment by DanielRuf** [comment]
Right, I'll probably also ping the Yarn team.

**Comment by lirantal** [comment]
Cool. What did you mean by the URL check?

**Comment by DanielRuf** [comment]
https://github.com/DanielRuf/onload-check has a check for URLs of dependencies in package.json (needs lockfile / runtime check too) which would warn for example in cases like pm2.

**Comment by lirantal** [comment]
Ahh I see. So that's more of a linter thing for a project, that would warn about the use of dependencies from ad-hoc URLs like GitHub, instead of from a registry. That definitely has a place, not too sure it fits with npq though which is meant to be more of an install-time precaution.
