### ISSUE TITLE
Feature request: (offline) check for insecure packages

### ISSUE THREAD

**Issue by DanielRuf** [lirantal/npq#97]
## Expected Behavior

As a user I want to also check against the current advisories (see http://registry.npmjs.com/-/v1/search?text=is:insecure).

## Possible Solution

We can store offline copies or download a copy of http://registry.npmjs.com/-/v1/search?text=is:insecure and use it for a simple check, additionally to the check which uses the Snyk API - especially for offline usage (Verdaccio ;-) ).

## Context

In an offline context I still want to do some checks, especially the security related ones. Having an offline copy of a recent version of all insecure packages might be really helpful.

**Comment by lirantal** [comment]
Good idea. We could also combine from several sources such as the Node.js Security WG. I would say the complexity then would be to handle the version range logic ourselves.
