### ISSUE TITLE
CLI should support passing --ignore-scripts and other arguments to npm

### ISSUE THREAD

**Issue by lirantal** [lirantal/npq#99]
The npq-hero CLI as an alias to npm isn't passing forward to the npm cli arguments like `--ignore-scripts` and such.

## Expected Behavior
Running `npm install somepackage --ignore-scripts false` should pass the ignore-scripts argument successfully to the npm cli

## Current Behavior
Running `npm install somepackage --ignore-scripts false` should pass the `--ignore-scripts false` argument and value to the npm CLI but it gets swalloed by the npq-hero cli that wraps it.

## Possible Solution
Update npq-hero's supported list of arguments to pass forward

## Steps to Reproduce (for bugs)
provided above in current behavior

## Your Environment
* Version used: 1.14.4
* Environment name and version (e.g. Chrome 39, Node.js 5.4): Node.js 10.13.0
* Operating System and version (desktop or mobile): MacOS

**Comment by DanielRuf** [comment]
Would this directly pass `process.argv` to the underlying CLI? Otherwise "Update npq-hero's supported list of arguments to pass forward" gets cumbersome in the future (adding more "whitelisted" parameters / arguments).

**Comment by lirantal** [comment]
Indeed. I'll test this out and see about improving.
